### ISSUE TITLE
controller placement in SD-MANET

### ISSUE THREAD

**Issue by gaovivid** [ZAHID188/Mininet-Wifi_2024#1]
Hello, have you conducted any research on controller placement in SD-MANET (Software-Defined Mobile Ad Hoc Networks)？

**Comment by ZAHID188** [comment]
can you tell me what do you want to do specifically?

**Comment by gaovivid** [comment]
Hello, I would like to use Mininet-WiFi to simulate a realistic mobile ad hoc network (MANET) topology. My goal is to deploy controllers on different devices within the topology and evaluate the impact of controller placement on network performance, specifically in terms of latency and throughput.

**Comment by ZAHID188** [comment]
For adhoc topology this is the basic code and you can customize the topology whatever the way you want

```
 net.addLink(sta1, cls=adhoc, intf='sta3-wlan0',
                ssid='adhocNet', mode='g', channel=5,
                ht_cap='HT40+', **kwargs) 

```
For mobillity they have some model. I've provided a sample for more - [check  this link](https://github.com/ramonfontes/mn-wifi-ebook/blob/main/beginner.md#mobility-models)
```
net.setMobilityModel(time=0, model='RandomDirection',
                         max_x=100, max_y=100, seed=20)
```
for monitoring [check this sflow](https://github.com/ramonfontes/mn-wifi-ebook/blob/main/expert.md#traffic-monitoring-with-sflow-rt) and also use other iperf  or CLI commands for measuring latency and throughput. you can check this  [documentation](https://github.com/ramonfontes/mn-wifi-ebook/blob/main/background.md)
